#!/bin/sh

##############################################################################
# Gradle start up script for POSIX generated by Gradle.
##############################################################################

APP_HOME=$( cd -P "$( dirname "$0" )" > /dev/null && pwd )

APP_NAME="Gradle"
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

warn () { echo "$*"; } >&2
die () { echo; echo "$*"; echo; exit 1; } >&2

if [ -n "$JAVA_HOME" ]; then
    if [ -x "$JAVA_HOME/jre/sh/java" ]; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ]; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD="java"
    command -v java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and 'java' command could not be found."
fi

CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$CLASSPATH" ]; then
    die "ERROR: gradle-wrapper.jar tidak ditemukan di gradle/wrapper/. Lihat README.md bagian 'Gradle Wrapper' untuk cara mendapatkannya (tidak bisa disertakan langsung karena file biner)."
fi

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
  "-Dorg.gradle.appname=$APP_NAME" \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain "$@"
